# To create a user for this webapp, run the following from PG's SQL console:
#
#   CREATE USER arachni WITH PASSWORD 'secret' CREATEDB;
#
# (Update the credentials in both the above SQL query and the bellow settings appropriately.)

development:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: arachni_development
  pool: 50
  password: "<%= Figaro.env.POSTGRES_DB_PASSWORD %>"
  username: "<%= Figaro.env.POSTGRES_DB_USERNAME %>"

test: &test
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: arachni_test
  pool: 50
  password: "<%= Figaro.env.POSTGRES_DB_PASSWORD %>"
  username: "<%= Figaro.env.POSTGRES_DB_USERNAME %>"

production:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: arachni_production
  pool: 50
  password: "<%= Figaro.env.POSTGRES_DB_PASSWORD %>"
  username: "<%= Figaro.env.POSTGRES_DB_USERNAME %>"

cucumber:
  <<: *test
